### ISSUE TITLE
Asking for help running an example for intersection

### ISSUE THREAD

**Issue by danieldietrich** [kazu-yamamoto/llrbtree#4]
Hello,

thank you for open-sourcing your RedBlackTree algorithm.

I've created a Java implementation based on the book "Purely Functional Data Structures" by Chris Okasaki. While searching for the missing methods, like delete, I stumbled upon this repository and implemented some of this ideas in Java (non-commercial). [Here](https://github.com/vavr-io/vavr/blob/64076ce0498c5bd504f7877b50a28dad8c7e14ce/vavr/src/main/java/io/vavr/collection/RedBlackTree.java) is my current implementation.

There seems to be abug in my intersection implementation. I've double checked it and compared it with your Haskell implementation but I can't find a difference. There might be the risk, that your Haskell implementation also suffers from the counter-example of our [issue](https://github.com/vavr-io/vavr/issues/2098).

I don't ask you for looking into our code but maybe you are interested in double-checking if our counter-example works for your algorithm. I would do it myself but I'm not that familiar with setting up a Haskell build environment, it would take hours for me. Most probably it is a no-brainer for you.

```
// informal, using the natural ordering
tree1 : 1462193440, 0, 2147483647, -2147483648, 0, 637669539, -1612766076, -1, 1795938819, 1, 0, -420800448, -2147483648, 497885405, 0, 1084073832, 1, 1439964148, 1961646330
tree2 : -1, 1, 2147483647, -1434983536, -2147483648, -1452486079, 1365799971, 231691980, -1780534767, -2147483648, 1448658704, 0, 1526591298

// leads to a constraint violation, there is a red node where an empty tree is expected
intersection(tree1, tree2)
```

Thank you.

Best regards,

Daniel

**Comment by ummels** [comment]
Hi Daniel, I don't think this example exhibits the bug (please double-check in vavr). Actually, the only examples I found where the bug occurs are examples with more than two sets involved. For example:

```
tree1: 8, 14, 0, 7, 9, 3
tree2: 7, 9, 14, 6, 0, 5, 11, 10, 4, 12, 8, 13
tree3: 1, 2

// exhibits the bug
intersection(intersection(tree1, tree2), tree3)

// On the other hand, this correctly results in the empty set
intersection(tree1, intersection(tree2, tree3))
```

**Comment by danieldietrich** [comment]
@ummels thank you, this helps!

**Comment by kazu-yamamoto** [comment]
```haskell
> let tree1 = [1462193440, 0, 2147483647, -2147483648, 0, 637669539, -1612766076, -1, 1795938819, 1, 0, -420800448, -2147483648, 497885405, 0, 1084073832, 1, 1439964148, 1961646330]
> let tree2 = [-1, 1, 2147483647, -1434983536, -2147483648, -1452486079, 1365799971, 231691980, -1780534767, -2147483648, 1448658704, 0, 1526591298]
> tree1 `intersection` tree2
Node B 2 (Node B 1 (Node R 1 Leaf (-2147483648) Leaf) (-1) Leaf) 0 (Node B 1 (Node R 1 Leaf 1 Leaf) 2147483647 Leaf)

**Comment by kazu-yamamoto** [comment]
```haskell
> let tree1 = fromList [8, 14, 0, 7, 9, 3]
> let tree2 = fromList [7, 9, 14, 6, 0, 5, 11, 10, 4, 12, 8, 13]
> let tree3 = fromList [1, 2]
> (tree1 `intersection` tree2) `intersection` tree3
Leaf
> tree1 `intersection` (tree2 `intersection` tree3)
Leaf
```

**Comment by kazu-yamamoto** [comment]
These are the results of your examples.
@danieldietrich Do you think these are incorrect?

**Comment by ummels** [comment]
Looks correct to me, so the bug is probably only in the Java implementation.

@kazu-yamamoto What is the result of `tree1 intersection tree2` in the second example?

**Comment by danieldietrich** [comment]
@kazu-yamamoto thank you for doing the test, it looks allright!

**Comment by kazu-yamamoto** [comment]
Here it is:

```
> let tree1 = fromList [8, 14, 0, 7, 9, 3]
> let tree2 = fromList [7, 9, 14, 6, 0, 5, 11, 10, 4, 12, 8, 13]
> tree1 `intersection` tree2
Node B 2 (Node B 1 (Node R 1 Leaf 0 Leaf) 7 Leaf) 8 (Node B 1 (Node R 1 Leaf 9 Leaf) 14 Leaf)
> printSet (tree1 `intersection` tree2)
B 8 (2)
+ B 7 (1)
  + R 0 (1)
    + 
    + 
  + 
+ B 14 (1)
  + R 9 (1)
    + 
    + 
  + 

```

**Comment by danieldietrich** [comment]
@kazu-yamamoto Thank you! I think the colouring within my tree construction does not work correctly. Could you please print the constructed `tree1` and `tree2` of your last [comment](https://github.com/kazu-yamamoto/llrbtree/issues/4#issuecomment-334332931)? It would help me to verify my construction routine.

Many thanks for your helping hand!
